"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (if present).
load_dotenv(BASE_DIR / ".env")

# External API keys
ORS_API_KEY = os.getenv("ORS_API_KEY", "")


import logging

DEFAULT_TRUCK_AVG_MPH = 55.0


def _truck_avg_mph(raw: str | None) -> float:
    """Average truck speed used to turn route distance into driving time; 30-75 mph, else the default (with a warning)."""
    if raw is None or not raw.strip():
        return DEFAULT_TRUCK_AVG_MPH
    try:
        value = float(raw)
    except ValueError:
        value = float("nan")
    if not 30 <= value <= 75:  # also false for NaN
        logging.getLogger(__name__).warning(
            "TRUCK_AVG_MPH=%r is not a number from 30 to 75; using %s mph.", raw, DEFAULT_TRUCK_AVG_MPH
        )
        return DEFAULT_TRUCK_AVG_MPH
    return value


# Average speed for driving time. ORS's own durations are not used: its truck profile averages about 40 mph.
TRUCK_AVG_MPH = _truck_avg_mph(os.getenv("TRUCK_AVG_MPH"))


# Security settings are environment-driven (see backend/.env.example).
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


def _env_list(name: str, default: str) -> list[str]:
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY environment variable is required. Set it in backend/.env or the host environment."
    )

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")

# CORS: explicit allowlist. The API is stateless and the frontend sends no credentials.
# Requires `django-cors-headers` installed.
CORS_ALLOWED_ORIGINS = _env_list("CORS_ALLOWED_ORIGINS", "http://localhost:3000")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'trip',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Rate limiting for POST /api/plan/ (each plan spends OpenRouteService free-tier quota). Per client IP.
# The app sits behind the host's reverse proxy, so the client IP comes from X-Forwarded-For: THROTTLE_NUM_PROXIES is
# how many proxies append to it (the client is that many entries from the right). 0 trusts only the socket address.
# Cloudflare's published edge address ranges. When the proxy hop that reaches the app is one of these, the visitor's own
# address is read from the CF-Connecting-IP header (which only Cloudflare can set on such a request).
# Source: https://www.cloudflare.com/ips-v4 and https://www.cloudflare.com/ips-v6, fetched 2026-10-07 and supplied by
# the project owner. Cloudflare changes these rarely; re-check them occasionally.
CLOUDFLARE_IP_RANGES = (
    # IPv4
    "173.245.48.0/20",
    "103.21.244.0/22",
    "103.22.200.0/22",
    "103.31.4.0/22",
    "141.101.64.0/18",
    "108.162.192.0/18",
    "190.93.240.0/20",
    "188.114.96.0/20",
    "197.234.240.0/22",
    "198.41.128.0/17",
    "162.158.0.0/15",
    "104.16.0.0/13",
    "104.24.0.0/14",
    "172.64.0.0/13",
    "131.0.72.0/22",
    # IPv6
    "2400:cb00::/32",
    "2606:4700::/32",
    "2803:f800::/32",
    "2405:b500::/32",
    "2405:8100::/32",
    "2a06:98c0::/29",
    "2c0f:f248::/32",
)

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_RATES": {"plan": os.environ.get("PLAN_THROTTLE_RATE", "15/hour")},
    "NUM_PROXIES": int(os.environ.get("THROTTLE_NUM_PROXIES", "1")),
    "EXCEPTION_HANDLER": "trip.api_errors.exception_handler",
}


# Application logs (trip.*) go to stdout at INFO so the host's log viewer shows them; Django's own loggers keep their defaults.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"plain": {"format": "%(asctime)s %(levelname)s %(name)s: %(message)s"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "plain"}},
    "loggers": {"trip": {"handlers": ["console"], "level": "INFO", "propagate": False}},
}
